DROP SCHEMA IF EXISTS db_seguridad;

CREATE SCHEMA db_seguridad;

USE db_seguridad;

CREATE TABLE controles(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	codigo VARCHAR(20) NOT NULL,
	descripcion TEXT NOT NULL
);

CREATE TABLE vulnerabilidades(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	codigo VARCHAR(20) NOT NULL,
	descripcion TEXT NOT NULL
);

CREATE TABLE grupo_activos(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	codigo VARCHAR(20) NOT NULL
);

CREATE TABLE amenazas(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	codigo VARCHAR(20) NOT NULL,
	descripcion TEXT NOT NULL
);

CREATE TABLE riesgos(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	codigo VARCHAR(20) NOT NULL,
	descripcion TEXT NOT NULL
);

CREATE TABLE agentes(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	codigo VARCHAR(20) NOT NULL,
	descripcion TEXT NOT NULL
);

CREATE TABLE ubicaciones(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	codigo VARCHAR(20) NOT NULL
);

CREATE TABLE capas(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	codigo VARCHAR(20) NOT NULL
);

CREATE TABLE criticidades(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	grado INT NOT NULL,
	descripcion TEXT NOT NULL
);

CREATE TABLE tipo_activos(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	nombre VARCHAR(20) NOT NULL
);

